import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:price_explorer/services/pricing.dart';

/// Runs `pricing.dart` over every entry in the database and compares the
/// result to what Google Sheets computed for the same entry.
///
/// The spreadsheet is the source of truth, so a disagreement here is a bug in
/// our reimplementation. The corpus is regenerated by
/// `python tools/validate_calculations.py`; it deliberately contains only
/// numbers, so this test needs no database, no browser and no WASM.
///
/// Every entry now agrees, and the one that used to not is worth recording.
///
/// Entry 7292 was listed here for months. Its measure is spelled `Garb, Steel
/// [?81 lb?]` with two literal question marks, and in the August workbook the
/// spreadsheet's own lookup failed on it: `Total Grams` came through blank,
/// the valuation count cached as zero and the per-unit figure as `#DIV/0!`,
/// while our implementation resolved the measure and produced an answer.
///
/// In the researcher's current workbook the same row resolves to 36741.00185
/// and 0.1905, with the spelling unchanged. So the sheet had simply failed to
/// recalculate that cell, our reading was right all along, and the two now
/// agree. The list is kept, empty, because this test reports a *recovered*
/// divergence as loudly as a new one, and that is how this was noticed.
const _knownDivergentEntries = <int>{};

const _tolerance = 1e-6;

class _Row {
  _Row(this.entry, this.values);
  final int entry;
  final Map<String, double?> values;

  double? operator [](String key) => values[key];
}

List<_Row> _loadCorpus() {
  final file = File('test/fixtures/calculation_corpus.csv');
  if (!file.existsSync()) {
    fail('Missing ${file.path}. Regenerate it with '
        '`python tools/validate_calculations.py`.');
  }
  final lines = file.readAsLinesSync();
  final header = lines.first.split(',');
  return [
    for (final line in lines.skip(1))
      if (line.trim().isNotEmpty)
        () {
          final cells = line.split(',');
          final values = <String, double?>{};
          for (var i = 0; i < header.length; i++) {
            final raw = i < cells.length ? cells[i].trim() : '';
            values[header[i]] = raw.isEmpty ? null : double.parse(raw);
          }
          return _Row(values['entry']!.toInt(), values);
        }(),
  ];
}

bool _closeEnough(double? got, double? want) {
  if (want == null) return true; // spreadsheet cached an error; nothing to check
  if (got == null) return false;
  final scale = [want.abs(), got.abs(), 1e-12].reduce((a, b) => a > b ? a : b);
  return (got - want).abs() / scale < _tolerance;
}

void main() {
  final corpus = _loadCorpus();

  test('the corpus is present and complete', () {
    // 7,800 real entries. The Data sheet runs to 10,379 rows, but 7801 onward
    // are unfilled template rows carrying only dropdown defaults, and the ETL
    // skips them.
    expect(corpus.length, 7800,
        reason: 'expected the full database, got ${corpus.length} rows');
  });

  test('every entry matches the spreadsheet', () {
    final failures = <String>[];
    var compared = 0;

    for (final row in corpus) {
      final result = calculatePrice(
        quantities: [
          MeasuredQuantity(row['u1'], row['v1']),
          MeasuredQuantity(row['u2'], row['v2']),
          MeasuredQuantity(row['u3'], row['v3']),
        ],
        price: RecordedPrice(
            pounds: row['l'], shillings: row['s'], pence: row['d']),
        valuationMetric: row['valuation'],
        multiplierWorkers: row['mult'],
        outputXMetric: row['out_x'],
        outputYMetric: row['out_y'],
      );

      final checks = <String, (double?, double?)>{
        'total metric': (result.totalMetric, row['x_total']),
        'price in pence': (result.priceInPence, row['x_price']),
        'valuation count': (result.valuationCount, row['x_val_count']),
        'total sale': (result.totalSaleInPence, row['x_sale']),
        'output X value': (result.outputXValue, row['x_out_x']),
        'pence per output Y': (result.pencePerOutputY, row['x_per_y']),
      };

      final diverged = <String>[];
      for (final entry in checks.entries) {
        final (got, want) = entry.value;
        if (want != null) compared++;
        if (!_closeEnough(got, want)) {
          diverged.add('${entry.key}: got $got, spreadsheet says $want');
        }
      }

      if (diverged.isEmpty) {
        if (_knownDivergentEntries.contains(row.entry)) {
          failures.add(
              'entry ${row.entry} is listed as a known divergence but now '
              'agrees — remove it from _knownDivergentEntries.');
        }
      } else if (!_knownDivergentEntries.contains(row.entry)) {
        failures.add('entry ${row.entry}: ${diverged.join('; ')}');
      }
    }

    expect(compared, greaterThan(40000),
        reason: 'far fewer comparisons than expected — is the corpus truncated?');

    if (failures.isNotEmpty) {
      fail('${failures.length} entries disagree with the spreadsheet:\n'
          '${failures.take(20).join('\n')}');
    }
  });

  test('the proportion with no computable price matches the source', () {
    // 364 of the 7,800 entries cache no pence-per-output-Y. Reproducing that
    // exactly is the point: the gap is in the historical record, not in the
    // code.
    //
    // It was 395 against the August workbook. The 31 that gained an answer
    // are rows the researcher has since filled in or whose measure lookup the
    // sheet recalculated, 7292 among them. If this number moves again,
    // something in the source moved; find out what before changing it.
    final noCachedAnswer =
        corpus.where((r) => r['x_per_y'] == null).length;
    expect(noCachedAnswer, 364);

    final weAlsoHaveNoAnswer = corpus.where((r) {
      if (r['x_per_y'] != null) return false;
      final result = calculatePrice(
        quantities: [
          MeasuredQuantity(r['u1'], r['v1']),
          MeasuredQuantity(r['u2'], r['v2']),
          MeasuredQuantity(r['u3'], r['v3']),
        ],
        price: RecordedPrice(pounds: r['l'], shillings: r['s'], pence: r['d']),
        valuationMetric: r['valuation'],
        multiplierWorkers: r['mult'],
        outputYMetric: r['out_y'],
      );
      return result.pencePerOutputY == null;
    }).length;

    // Stated against the sheet's own count rather than a number typed in
    // here. The invariant is "we never answer where the source could not",
    // and writing it as a literal meant it had to be re-typed every time the
    // source moved, which is exactly when an assertion should be holding
    // still. It was `394` against a sheet with 395, the one gap being entry
    // 7292, where the spreadsheet had failed to recalculate and we had not.
    expect(weAlsoHaveNoAnswer, greaterThanOrEqualTo(noCachedAnswer),
        reason: 'we should decline to answer wherever the spreadsheet did');
  });
}
